steps:
  # Step 1: Terraform Init
  - name: hashicorp/terraform:1.7.5
    id: init
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform-multi-region-clean-trees/envs/prod
        terraform init \
          -backend-config="bucket=terraform-state-clean-trees" \
          -backend-config="prefix=multi-region-prod"

  # Step 2: Terraform Validate
  - name: hashicorp/terraform:1.7.5
    id: validate
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform-multi-region-clean-trees/envs/prod
        terraform validate

  # Step 3: Terraform Plan
  - name: hashicorp/terraform:1.7.5
    id: plan
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform-multi-region-clean-trees/envs/prod
        terraform plan -var="project_id=${_PROJECT_ID}" -out=tfplan

  # Step 4: Terraform Apply
  - name: hashicorp/terraform:1.7.5
    id: apply
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform-multi-region-clean-trees/envs/prod
        terraform apply -auto-approve tfplan

timeout: "1200s"

substitutions:
  _PROJECT_ID: "clean-trees-477813-n2"

serviceAccount: "540440108859@cloudbuild.gserviceaccount.com"


options:
  logging: CLOUD_LOGGING_ONLY

