steps:
  # Step 1: Terraform Init
  - name: hashicorp/terraform:1.7.5
    id: init
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd envs/prod
        terraform init \
          -backend-config="bucket=terraform-state-clean-trees" \
          -backend-config="prefix=multi-region-prod"

  # Step 2: Terraform Validate
  - name: hashicorp/terraform:1.7.5
    id: validate
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd envs/prod
        terraform validate

  # Step 3: Terraform Plan
  - name: hashicorp/terraform:1.7.5
    id: plan
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd envs/prod
        terraform plan -var=\"project_id=${_PROJECT_ID}\" -out=tfplan

  # Step 4: Terraform Apply
  - name: hashicorp/terraform:1.7.5
    id: apply
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd envs/prod
        terraform apply -auto-approve tfplan

timeout: "1200s"

# ✅ Custom substitution key fixed
substitutions:
  _PROJECT_ID: "clean-trees-477813-n2"

# Use your Cloud Build Service Account
serviceAccount: "cloud-build-user@clean-trees-477813-n2.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
