steps:
  - name: hashicorp/terraform:1.7.5
    id: init
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform-multi-region-clean-trees/envs/prod
        terraform init \
          -backend-config="bucket=terraform-state-clean-trees" \
          -backend-config="prefix=multi-region-prod"

  - name: hashicorp/terraform:1.7.5
    id: validate
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform-multi-region-clean-trees/envs/prod
        terraform validate

  - name: hashicorp/terraform:1.7.5
    id: plan
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform-multi-region-clean-trees/envs/prod
        terraform plan -var="project_id=${_PROJECT_ID}" -out=tfplan

  - name: hashicorp/terraform:1.7.5
    id: apply
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform-multi-region-clean-trees/envs/prod
        terraform apply -auto-approve tfplan

substitutions:
  _PROJECT_ID: "clean-trees-477813-n2"

serviceAccount: "projects/clean-trees-477813-n2/serviceAccounts/540440108859-compute@developer.gserviceaccount.com"


