steps:
  # Step 1: Set up Terraform
  - name: hashicorp/terraform:1.7.5
    id: init
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd envs/prod
        terraform init -backend-config="bucket=terraform-state-clean-trees" \
                       -backend-config="prefix=multi-region-prod"

  # Step 2: Terraform Validate
  - name: hashicorp/terraform:1.7.5
    id: validate
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd envs/prod
        terraform validate

  # Step 3: Terraform Plan
  - name: hashicorp/terraform:1.7.5
    id: plan
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd envs/prod
        terraform plan -out=tfplan

  # Step 4: Terraform Apply (auto-approve for CI/CD)
  - name: hashicorp/terraform:1.7.5
    id: apply
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd envs/prod
        terraform apply -auto-approve tfplan

timeout: "1200s"

substitutions:
  _TF_VAR_project_id: "clean-trees-477813-n2"

# Optional: use a Cloud Build Service Account with limited IAM permissions
serviceAccount: "cloud-build-user@clean-trees-477813-n2.iam.gserviceaccount.com"

# Store build logs in Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY
