steps:
  - name: hashicorp/terraform:1.7.5
    id: init
    dir: "multi-region-infra"
    entrypoint: sh
    args:
      - -c
      - |
        terraform init \
          -backend-config="bucket=terraform-state-clean-trees" \
          -backend-config="prefix=multi-region-prod"

  - name: hashicorp/terraform:1.7.5
    id: validate
    dir: "multi-region-infra"
    entrypoint: sh
    args:
      - -c
      - |
        terraform validate

  - name: hashicorp/terraform:1.7.5
    id: plan
    dir: "multi-region-infra"
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan \
          -var="project_id=${_PROJECT_ID}" \
          -out=tfplan

  - name: hashicorp/terraform:1.7.5
    id: apply
    dir: "multi-region-infra"
    entrypoint: sh
    args:
      - -c
      - |
        terraform apply -auto-approve tfplan

timeout: "1200s"

substitutions:
  _PROJECT_ID: "clean-trees-477813-n2"

serviceAccount: "cloud-build-user@clean-trees-477813-n2.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
